OpenNMS/opennms-cloud-plugin

karaf-features/pom.xml
karaf-features/src/main/resources/features.xml
plugin/src/main/java/org/opennms/plugins/cloud/tsaas/TsaasStorage.java
plugin/src/main/resources/OSGI-INF/blueprint/blueprint.xml
plugin/src/test/java/org/opennms/plugins/cloud/tsaas/TsaasStorageTest.java
plugin/src/test/java/org/opennms/plugins/cloud/tsaas/testserver/TestserverMain.java
pom.xml

[Jira DC-13](https://issues.opennms.org/browse/DC-13)

DC-13: Fix Osgi Dependency issues

---

it-test/pom.xml
it-test/src/test/java/org/opennms/plugins/cloud/tsaas/KarafShell.java
it-test/src/test/java/org/opennms/plugins/cloud/tsaas/SshClient.java
it-test/src/test/java/org/opennms/plugins/cloud/tsaas/StreamGobbler.java
it-test/src/test/java/org/opennms/plugins/cloud/tsaas/TsaasStorageIT.java
it-test/src/test/java/org/opennms/plugins/cloud/tsaas/jsch/SLF4JLogger.java
it-test/src/test/resources/docker-compose.yaml
it-test/src/test/resources/log4j2.xml
plugin/pom.xml
plugin/src/test/java/org/opennms/plugins/cloud/tsaas/TsaasStorageTest.java
pom.xml

Jira: https://issues.opennms.org/browse/DC-14
Starts a OpenNMS instance in Docker and installs the plugin.
The purpose of the test is to check if the plugin can be installed and thus detect any Osgi wiring problems.

DC-14: Integration Test: Run Plugin in OpenNMS

---

it-test/src/test/resources/docker-compose.yaml
pom.xml

Jira: https://issues.opennms.org/browse/DC-22

DC-22: Bump OAI version to latest version: 0.8.1-SNAPSHOT

---

plugin/src/main/java/org/opennms/plugins/cloud/tsaas/TsaasStorage.java

This PR makes the use of the trust store optional. If no trust store is found it will default to the JVMs trust store.

DC-20: Add mTLS support for Cloud Plugin: make trust store optional

---

plugin/src/main/java/org/opennms/plugins/cloud/tsaas/grpc/GrpcObjectMapper.java

Make the plugin more robust against missing data
Jira: https://issues.opennms.org/browse/DC-29

DC-29: Query failed on several graphs (random behavior)

---

plugin/src/main/java/org/opennms/plugins/cloud/tsaas/TsaasConfig.java
plugin/src/main/java/org/opennms/plugins/cloud/tsaas/TsaasStorage.java
plugin/src/main/resources/OSGI-INF/blueprint/blueprint.xml
plugin/src/test/java/org/opennms/plugins/cloud/tsaas/TsaasStorageBatchStoringTest.java
plugin/src/test/java/org/opennms/plugins/cloud/tsaas/TsaasStorageTest.java
plugin/src/test/java/org/opennms/plugins/cloud/tsaas/TsaasStorageWithMtlsTest.java
plugin/src/test/java/org/opennms/plugins/cloud/tsaas/testserver/TestserverMain.java
plugin/src/test/java/org/opennms/plugins/cloud/tsaas/testserver/TsaasServer.java

Jira: https://issues.opennms.org/browse/DC-24

DC-24: Implement batching to reduce the number of requests to the gateway

---

it-test/src/test/resources/docker-compose.yaml
plugin/src/main/java/org/opennms/plugins/cloud/tsaas/TsaasStorage.java
plugin/src/main/java/org/opennms/plugins/cloud/tsaas/grpc/GrpcObjectMapper.java
plugin/src/test/java/org/opennms/plugins/cloud/tsaas/testserver/TimeseriesGrpcImpl.java

Depends on https://github.com/OpenNMS-Cloud/TSaaS/pull/35
Jira: https://issues.opennms.org/browse/DC-122
Needs to be synced with Cloud Gateway

DC-122: Deduplicate Metric in SearchResult

---

plugin/src/main/java/org/opennms/plugins/cloud/tsaas/TsaasStorage.java

https://issues.opennms.org/browse/DC-134

DC-134: align buffer size with TSaaS server

---

it-test/src/test/resources/docker-compose.yaml
plugin/src/test/java/org/opennms/plugins/cloud/tsaas/TsaasStorageNetworkProblemTest.java
pom.xml

Jira: https://issues.opennms.org/browse/DC-193

DC-193:  Cloud Plugin: Make sure RPC reconnects after a failure

---

plugin/src/main/java/org/opennms/plugins/cloud/tsaas/GrpcConnection.java
plugin/src/main/java/org/opennms/plugins/cloud/tsaas/TsaasStorage.java
plugin/src/main/java/org/opennms/plugins/cloud/tsaas/shell/MetricWrite.java
plugin/src/test/java/org/opennms/plugins/cloud/tsaas/TsaasStorageNetworkProblemTest.java
plugin/src/test/java/org/opennms/plugins/cloud/tsaas/TsaasStorageTest.java
plugin/src/test/java/org/opennms/plugins/cloud/tsaas/TsaasStorageWithMtlsTest.java
plugin/src/test/java/org/opennms/plugins/cloud/tsaas/shell/MetricWriteTest.java

https://issues.opennms.org/browse/DC-212

DC-212: Fix Sonar Bugs

---

plugin/src/main/java/org/opennms/plugins/cloud/tsaas/GrpcConnection.java
plugin/src/main/java/org/opennms/plugins/cloud/tsaas/SecureCredentialsVaultUtil.java
plugin/src/main/java/org/opennms/plugins/cloud/tsaas/config/CertificateImporter.java
plugin/src/main/java/org/opennms/plugins/cloud/tsaas/grpc/GrpcObjectMapper.java
plugin/src/main/java/org/opennms/plugins/cloud/tsaas/grpc/comp/ZStdGrpcCodec.java
plugin/src/test/java/org/opennms/plugins/cloud/tsaas/CloudHealthCheckTest.java
plugin/src/test/java/org/opennms/plugins/cloud/tsaas/TsaasStorageWithMtlsTest.java
plugin/src/test/java/org/opennms/plugins/cloud/tsaas/config/CertificateImporterTest.java
plugin/src/test/java/org/opennms/plugins/cloud/tsaas/config/ConfigZipExtractorTest.java
plugin/src/test/java/org/opennms/plugins/cloud/tsaas/shell/MetricWriteTest.java
plugin/src/test/java/org/opennms/plugins/cloud/tsaas/testserver/TimeseriesGrpcImpl.java

Jira: https://issues.opennms.org/browse/DC-212

DC-212: Fix Sonar Bugs: Part 2

---

README.md
it-test/src/test/resources/docker-compose.yaml
plugin/src/main/java/org/opennms/plugins/cloud/config/CertificateImporter.java
plugin/src/main/java/org/opennms/plugins/cloud/config/ConfigurationManager.java
plugin/src/main/java/org/opennms/plugins/cloud/config/PasAccess.java
plugin/src/main/java/org/opennms/plugins/cloud/config/PrerequisiteChecker.java
plugin/src/main/java/org/opennms/plugins/cloud/config/SecureCredentialsVaultUtil.java
plugin/src/main/java/org/opennms/plugins/cloud/config/shell/ConfigureCloud.java
plugin/src/main/java/org/opennms/plugins/cloud/grpc/GrpcConnectionConfig.java
plugin/src/main/resources/OSGI-INF/blueprint/blueprint.xml
plugin/src/test/java/org/opennms/plugins/cloud/config/CertificateImporterTest.java
plugin/src/test/java/org/opennms/plugins/cloud/config/ConfigManagerTest.java
plugin/src/test/java/org/opennms/plugins/cloud/config/ConfigServiceTest.java
plugin/src/test/java/org/opennms/plugins/cloud/config/ConfigZipExtractorTest.java
plugin/src/test/java/org/opennms/plugins/cloud/config/ConfigurationManagerCredentialsImportTest.java
plugin/src/test/java/org/opennms/plugins/cloud/config/PrerequisiteCheckerTest.java
pom.xml

Jira: https://issues.opennms.org/browse/DC-266
Fixes also the default token key name.

DC-266: Get Environement and OpenNMS system Id and provide to access service

---

README.md
karaf-features/pom.xml
karaf-features/src/main/resources/features.xml
plugin/pom.xml
plugin/src/main/java/org/opennms/plugins/cloud/config/ConfigurationManager.java
plugin/src/main/java/org/opennms/plugins/cloud/config/Housekeeper.java
plugin/src/main/java/org/opennms/plugins/cloud/config/TokenUtil.java
plugin/src/main/resources/OSGI-INF/blueprint/blueprint.xml
plugin/src/test/java/org/opennms/plugins/cloud/config/ConfigManagerTest.java
plugin/src/test/java/org/opennms/plugins/cloud/config/ConfigurationManagerCredentialsImportTest.java
plugin/src/test/java/org/opennms/plugins/cloud/config/ConfigurationManagerTest.java
plugin/src/test/java/org/opennms/plugins/cloud/config/HousekeeperTest.java
plugin/src/test/java/org/opennms/plugins/cloud/config/TokenUtilTest.java
plugin/src/test/java/org/opennms/plugins/cloud/testserver/ConfigGrpcImpl.java
pom.xml
wrap/jwt/pom.xml
wrap/pom.xml

Jira: https://issues.opennms.org/browse/DC-278

DC-278: Renew token

---

README.md
plugin/src/main/java/org/opennms/plugins/cloud/config/CertUtil.java
plugin/src/main/java/org/opennms/plugins/cloud/config/ConfigurationManager.java
plugin/src/main/java/org/opennms/plugins/cloud/config/Housekeeper.java
plugin/src/main/java/org/opennms/plugins/cloud/config/PasAccess.java
plugin/src/main/java/org/opennms/plugins/cloud/config/PrerequisiteChecker.java
plugin/src/main/java/org/opennms/plugins/cloud/config/shell/RenewCertificate.java
plugin/src/main/java/org/opennms/plugins/cloud/grpc/CloseUtil.java
plugin/src/main/java/org/opennms/plugins/cloud/grpc/GrpcConnection.java
plugin/src/main/java/org/opennms/plugins/cloud/rest/CloudConfigRestServiceImpl.java
plugin/src/main/java/org/opennms/plugins/cloud/srv/tsaas/TsaasStorage.java
plugin/src/test/java/org/opennms/plugins/cloud/config/CertUtilTest.java
plugin/src/test/java/org/opennms/plugins/cloud/config/ConfigurationManagerTest.java
plugin/src/test/java/org/opennms/plugins/cloud/config/HousekeeperTest.java
plugin/src/test/java/org/opennms/plugins/cloud/config/PasAccessTest.java
plugin/src/test/java/org/opennms/plugins/cloud/grpc/CloseUtilTest.java
plugin/src/test/java/org/opennms/plugins/cloud/rest/CloudConfigRestServiceImplTest.java
plugin/src/test/java/org/opennms/plugins/cloud/srv/tsaas/CloudHealthCheckTest.java
plugin/src/test/java/org/opennms/plugins/cloud/testserver/ConfigGrpcImpl.java
pom.xml

Jira: https://issues.opennms.org/browse/DC-279

DC-279: Renew certificate

---

.circleci/config.yml
it-test/pom.xml
it-test/src/test/java/org/opennms/plugins/cloud/tsaas/TsaasStorageIT.java
it-test/src/test/resources/docker-compose.yaml
it-test/src/test/resources/log4j2.xml

Jira: https://issues.opennms.org/browse/DC-316

DC-316: Fix bug with docker container

---

README.md

https://issues.opennms.org/browse/DC-302

DC-302: Create how to for the full plugin installation process

---

plugin-common/src/main/java/org/opennms/plugins/cloud/grpc/GrpcConnection.java
plugin-common/src/main/java/org/opennms/plugins/cloud/grpc/GrpcConnectionConfig.java
plugin-core/src/main/ui/package.json

also fixes broken vue build
Jira: https://issues.opennms.org/browse/DC-346

DC-346: Remove PLAIN_TEXT Grpc communication

---

pom.xml

Jira: https://issues.opennms.org/browse/DC-309

DC-309: Sort out GRPC dependencies

---

checkstyle/pom.xml

This PR tries to fix the release which was broken by https://github.com/OpenNMS/opennms-cloud-plugin/pull/63
Jira: https://issues.opennms.org/browse/DC-311

DC-311: Introduce Checkstyle: fix build information

---

.circleci/config.yml
.circleci/scripts/publish-cloudsmith.sh
assembly/opennms-deb/pom.xml
assembly/opennms-rpm/pom.xml
assembly/sentinel-deb/pom.xml
assembly/sentinel-rpm/pom.xml
it-test/src/test/java/org/opennms/plugins/cloud/ittest/EndToEndIt.java
it-test/src/test/resources/docker-compose.yaml
plugin-common/src/main/resources/OSGI-INF/blueprint/blueprint.xml
pom.xml

To save time for release we combine few issue.
https://issues.opennms.org/browse/DC-372
https://issues.opennms.org/browse/DC-406
https://issues.opennms.org/browse/DC-405

DC-372: Use OpenNMS Integration Api (OIA) version in plugin packages

---

.circleci/scripts/publish-cloudsmith.sh

https://issues.opennms.org/projects/DC/issues/DC-410?filter=allissues

DC-410: fix cloudsmith publish location

---

assembly/kar/pom.xml
assembly/opennms-deb/pom.xml
assembly/opennms-rpm/pom.xml
assembly/pom.xml
assembly/sentinel-deb/pom.xml
assembly/sentinel-rpm/pom.xml
checkstyle/pom.xml
it-test/pom.xml
it-test/src/test/java/org/opennms/plugins/cloud/ittest/EndToEndIt.java
it-test/src/test/resources/docker-compose.yaml
karaf-features/pom.xml
plugin-common/pom.xml
plugin-core/pom.xml
pom.xml
wrap/grpc/pom.xml
wrap/jwt/pom.xml
wrap/pom.xml

https://issues.opennms.org/browse/DC-411

DC-411: bump up version for cloud plugin after release (1.1.0)

---

.circleci/config.yml
.circleci/scripts/publish-cloudsmith.sh
assembly/common-resources/etc/featuresBoot.d/plugin-cloud.boot
assembly/common-resources/scripts/postinst.opennms.deb.sh
assembly/common-resources/scripts/postinst.opennms.rpm.sh
assembly/kar/pom.xml
assembly/opennms-deb/pom.xml
assembly/opennms-rpm/pom.xml
assembly/pom.xml
assembly/sentinel-deb/pom.xml
assembly/sentinel-rpm/pom.xml
checkstyle/pom.xml
it-test/pom.xml
it-test/src/test/java/org/opennms/plugins/cloud/ittest/EndToEndIt.java
it-test/src/test/resources/docker-compose.yaml
karaf-features/pom.xml
plugin-common/pom.xml
plugin-core/pom.xml
pom.xml
wrap/grpc/pom.xml
wrap/jwt/pom.xml
wrap/pom.xml

https://issues.opennms.org/browse/DC-419

DC-419: make sure opennms-plugin-cloud is installed on H31 by default

---

.circleci/config.yml
.circleci/scripts/publish-cloudsmith.sh
assembly/kar/pom.xml
assembly/opennms-deb/pom.xml
assembly/opennms-rpm/pom.xml
assembly/pom.xml
assembly/sentinel-deb/pom.xml
assembly/sentinel-rpm/pom.xml
checkstyle/pom.xml
it-test/pom.xml
it-test/src/test/java/org/opennms/plugins/cloud/ittest/EndToEndIt.java
it-test/src/test/resources/docker-compose.yaml
karaf-features/pom.xml
plugin-common/pom.xml
plugin-core/pom.xml
pom.xml
wrap/grpc/pom.xml
wrap/jwt/pom.xml
wrap/pom.xml

merge back to release-1.x and bump ver

Release 1.0.2

---

assembly/common-resources/scripts/postinst.opennms.deb.sh
assembly/common-resources/scripts/postinst.opennms.rpm.sh

should address the permission errors in [NMS-15007](https://issues.opennms.org/browse/NMS-15007)

NMS-15007: fix permissions on featuresBoot.d, harden RUNAS setting

---

it-test/src/test/java/org/opennms/plugins/cloud/ittest/EndToEndIt.java
it-test/src/test/resources/docker-compose.yaml

https://issues.opennms.org/browse/DC-383

DC-383: make sure example property file handled properly

---

plugin-common/pom.xml
plugin-common/src/main/java/org/opennms/plugins/cloud/grpc/CloudLogService.java
plugin-common/src/main/java/org/opennms/plugins/cloud/grpc/CloudLogServiceUtil.java
plugin-common/src/main/java/org/opennms/plugins/cloud/grpc/GrpcConnection.java
plugin-common/src/main/java/org/opennms/plugins/cloud/grpc/GrpcExecutionHandler.java
plugin-common/src/main/java/org/opennms/plugins/cloud/grpc/TraceParentHeader.java
plugin-common/src/main/java/org/opennms/plugins/cloud/grpc/TraceParentHeaderGenerator.java
plugin-common/src/test/java/org/opennms/plugins/cloud/grpc/CloudLogServiceTestUtil.java
plugin-common/src/test/java/org/opennms/plugins/cloud/grpc/GrpcExecutionHandlerTest.java
plugin-common/src/test/java/org/opennms/plugins/cloud/grpc/LogEntryUtilTest.java
plugin-common/src/test/java/org/opennms/plugins/cloud/grpc/TraceIdGeneratorTest.java
plugin-common/src/test/java/org/opennms/plugins/cloud/testserver/GrpcTestServerInterceptor.java
pom.xml

- Added TraceParentHeader Class and TraceParentHeaderGenerator
- Updated necessary fields
- Tests

DC-458 Update Latency messages to include new values

---

plugin-core/src/main/ui/src/components/CloudPlugin.vue

Updating the verbiage of the deactivation modal based on discussions relating to the process

CLOUD-2790: Update verbiage of deactivation Modal

---

plugin-common/src/main/java/org/opennms/plugins/cloud/config/ConfigurationManager.java
plugin-core/src/main/java/org/opennms/plugins/cloud/rest/CloudConfigRestService.java
plugin-core/src/main/java/org/opennms/plugins/cloud/rest/CloudConfigRestServiceImpl.java
plugin-core/src/main/ui/package.json
plugin-core/src/main/ui/src/components/CloudPlugin.vue
plugin-core/src/main/ui/src/components/StatusBar.vue
plugin-core/src/test/java/org/opennms/plugins/cloud/rest/CloudConfigRestServiceImplTest.java

All of this code is being cherry picked over from main into release-1.x as requested by Andy

Cherry-picking Previous PR changes int release-1.x

---

plugin-common/src/main/java/org/opennms/plugins/cloud/config/ConfigurationManager.java
plugin-common/src/main/java/org/opennms/plugins/cloud/grpc/CloudLogService.java
plugin-common/src/main/java/org/opennms/plugins/cloud/srv/GrpcService.java
plugin-common/src/main/java/org/opennms/plugins/cloud/srv/faas/Faas.java
plugin-common/src/test/java/org/opennms/plugins/cloud/config/ConfigurationManagerTest.java
plugin-core/src/main/java/org/opennms/plugins/cloud/rest/CloudConfigRestService.java
plugin-core/src/main/java/org/opennms/plugins/cloud/rest/CloudConfigRestServiceImpl.java
plugin-core/src/test/java/org/opennms/plugins/cloud/rest/CloudConfigRestServiceImplTest.java

https://opennms.atlassian.net/browse/DC-465

DC-465: cloud plugin deactivate api

---

plugin-core/src/main/ui/src/components/CloudPlugin.vue

CLOUD-2803: moving periods inside the list items

---

plugin-common/src/main/resources/OSGI-INF/blueprint/blueprint.xml

https://opennms.atlassian.net/browse/DC-468

DC-468: CloudLogServiceConfig argument inverted

---

plugin-common/src/main/resources/OSGI-INF/blueprint/blueprint.xml

make sure the change also go into 1.x

DC-475 - Change the default hostname for PAS for dp-prod

---

assembly/opennms-deb/pom.xml
assembly/sentinel-deb/pom.xml
it-test/src/test/resources/package/deb/horizon/startHorizon.sh
it-test/src/test/resources/package/deb/sentinel/startSentinel.sh
it-test/src/test/resources/package/rpm/horizon/startHorizon.sh
it-test/src/test/resources/package/rpm/sentinel/startSentinel.sh
pom.xml

https://opennms.atlassian.net/browse/NMS-15013
It also fix package install test for https://opennms.atlassian.net/browse/DC-477

NMS-1501: fix debian package compression

---

.circleci/config.yml
assembly/opennms-deb/pom.xml
assembly/opennms-rpm/pom.xml
assembly/sentinel-deb/pom.xml
assembly/sentinel-rpm/pom.xml
checkstyle/pom.xml
plugin-core/src/main/ui/package.json
pom.xml

Adding more descriptions to OpenNMS and Sentinel packages

NMS-15229: opennms-plugin-cloud package should have a more complete description

---

.circleci/config.yml
.circleci/scripts/publish-cloudsmith.sh
RELEASING.md
assembly/opennms-deb/pom.xml
assembly/opennms-rpm/pom.xml
assembly/sentinel-deb/pom.xml
assembly/sentinel-rpm/pom.xml
it-test/pom.xml
it-test/src/test/resources/package/rpm/Dockerfile
karaf-features/src/main/resources/features.xml
plugin-core/src/main/ui/package.json
pom.xml

https://opennms.atlassian.net/browse/DC-558

DC-588: Sync release-1.x back to main branch
